import type { MatrixRole, Permission, PolicyOutcome } from "./types.js";

export const MATRIX_ROLES: readonly MatrixRole[] = [
  "org_admin",
  "ws_admin",
  "lead_inv",
  "investigator",
  "analyst",
  "reviewer",
  "contributor",
  "viewer",
  "auditor",
] as const;

export const PERMISSIONS_MATRIX: Record<Permission, Record<MatrixRole, PolicyOutcome>> = {
  "org.manage": {
    org_admin: "allow",
    ws_admin: "deny",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "org.billing": {
    org_admin: "allow",
    ws_admin: "deny",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "workspace.create": {
    org_admin: "allow",
    ws_admin: "deny",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "workspace.manage": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "workspace.members": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "workspace.policy": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "connector.configure": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "connector.use": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "investigation.create": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "investigation.read": {
    org_admin: "requires_approval",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "allow",
    contributor: "allow",
    viewer: "allow",
    auditor: "deny",
  },
  "investigation.define": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "own_only",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "investigation.scope": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "investigation.members": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "investigation.archive": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "source.admit": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "allow",
    viewer: "deny",
    auditor: "deny",
  },
  "source.withdraw": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "requires_approval",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "source.read": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "allow",
    contributor: "allow",
    viewer: "allow",
    auditor: "deny",
  },
  "source.purge": {
    org_admin: "requires_approval",
    ws_admin: "requires_approval",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "entity.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "deny",
    contributor: "allow",
    viewer: "deny",
    auditor: "deny",
  },
  "entity.edit": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "own_only",
    reviewer: "deny",
    contributor: "own_only",
    viewer: "deny",
    auditor: "deny",
  },
  "entity.merge": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "entity.unmerge": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "assertion.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "deny",
    contributor: "allow",
    viewer: "deny",
    auditor: "deny",
  },
  "assertion.validate": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "evidence.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "allow",
    contributor: "allow",
    viewer: "deny",
    auditor: "deny",
  },
  "evidence.withdraw": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "own_only",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "finding.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "finding.validate": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "finding.approve": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "deny",
    analyst: "deny",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "finding.retract": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "requires_approval",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "hypothesis.manage": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "contradiction.adjudicate": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "ai.query": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "allow",
    contributor: "allow",
    viewer: "deny",
    auditor: "deny",
  },
  "ai.promote": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "ai.agent_run": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "report.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "allow",
    analyst: "allow",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "report.approve": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "deny",
    analyst: "deny",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "report.publish": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "requires_approval",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "export.create": {
    org_admin: "deny",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "requires_approval",
    analyst: "deny",
    reviewer: "requires_approval",
    contributor: "deny",
    viewer: "deny",
    auditor: "deny",
  },
  "audit.read": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "allow",
    investigator: "own_only",
    analyst: "own_only",
    reviewer: "allow",
    contributor: "deny",
    viewer: "deny",
    auditor: "allow",
  },
  "audit.export": {
    org_admin: "allow",
    ws_admin: "allow",
    lead_inv: "deny",
    investigator: "deny",
    analyst: "deny",
    reviewer: "deny",
    contributor: "deny",
    viewer: "deny",
    auditor: "allow",
  },
};
