import { z } from "zod";

/**
 * RFC 9457 Problem Details for HTTP APIs (PRD §45.4).
 */
export const ProblemDetailsSchema = z.object({
  type: z.string().url().describe("A URI reference that identifies the problem type"),
  title: z.string().describe("A short, human-readable summary of the problem type"),
  status: z.number().int().min(100).max(599).describe("The HTTP status code generated by the origin server"),
  detail: z.string().describe("A human-readable explanation specific to this occurrence of the problem"),
  instance: z.string().optional().describe("A URI reference that identifies the specific occurrence of the problem"),
  request_id: z.string().describe("Unique identifier for request tracing and correlation"),
});

export type ProblemDetails = z.infer<typeof ProblemDetailsSchema>;
